### PR TITLE
update react peer dependencies to support react v17

### PR DESCRIPTION
**Pull request by thealphaversion**
This PR addresses https://github.com/jungsoft/materialui-daterange-picker/issues/28 and https://github.com/jungsoft/materialui-daterange-picker/issues/34 to update react peer dependencies so that we can use this package with React 17. 🎉

### CODE REVIEW

**Comment by thealphaversion** [comment]
Would be great if @jungrafael or any other maintainer can have a look! Thanks! 😄

**Comment by jungrafael** [comment]
hi @thealphaversion, thanks for the PR! I'll release a new version soon

**Comment by markamber** [comment]
> hi @thealphaversion, thanks for the PR! I'll release a new version soon

Can I do anything to help? This is a dependency of my project and I am trying to avoid forking it but we need to get on React 17.

**Comment by JoelGarcia99** [comment]
> > hi @thealphaversion, thanks for the PR! I'll release a new version soon
> 
> Can I do anything to help? This is a dependency of my project and I am trying to avoid forking it but we need to get on React 17.

Did you found any way to use it on React 17 without forking?

**Comment by markamber** [comment]
> > > hi @thealphaversion, thanks for the PR! I'll release a new version soon
> > 
> > 
> > Can I do anything to help? This is a dependency of my project and I am trying to avoid forking it but we need to get on React 17.
> 
> Did you found any way to use it on React 17 without forking?

No, I barely know how to fork it (as in, the most idiomatic way) Like should I just put in my project? or upload to NPM?

**Pull request merged**
