### PR TITLE
 justifyContent prop for Grid instead of justify

### PR DESCRIPTION
**Pull request by sreerajmp**
#24

### CODE REVIEW

**Comment by sreerajmp** [comment]
@jungrafael

**Review by NikolaDeveloper — APPROVED** [review]
This change makes it compatible with MUI v5

**Comment by jungrafael** [comment]
Thanks for the PR @sreerajmp!

**Comment by minro** [comment]
When is this planned for release?

**Comment by flzozaya** [comment]
Hello @jungrafael 
Looks like this change was merged into `master` branch. But it didn't actually make it to the latest `v1.1.92` release? - It is still passing `justify` instead of `justifyContent`.

`v1.1.92` tag 👉  https://github.com/jungsoft/materialui-daterange-picker/blob/1.1.92/package/src/components/Menu.tsx#L103
`master` branch 👉 https://github.com/jungsoft/materialui-daterange-picker/blob/master/package/src/components/Menu.tsx#L103

Would it be possible to release?

**Pull request merged**
