### PR TITLE
Also export DateRangePicker without Popper and ClickAwayListener

### PR DESCRIPTION
**Pull request by ffMathy**
This allows someone to automatically decide how the component should be shown.

@jungrafael let me know if there are any changes you want to have made.

### CODE REVIEW

**Comment by pedro-lb** [comment]
Hey there @ffMathy !

Thanks for your contribution! 🚀 

I'm afraid I can't merge this as it is - since we've changed the default export. This would result in a breaking change that would affect all current applications that use this dependency.

We still need to export `DateRangePickerExporter` as `DateRangePicker`, to keep compatibility. But we can certainly add another export for `DateRangePicker` (maybe call it `DateRangePickerComponent`?).

image

We'll merge as soon as these changes have been added.

**Comment by ffMathy** [comment]
Hey @pedro-lb I made the changes as requested.

**Comment by ffMathy** [comment]
@pedro-lb any ETA on when this can be merged and published to NPM?

Thanks in advance, and thank you for reviewing my PR so detailed.

**Comment by pedro-lb** [comment]
Thanks @ffMathy !

I'll publish a new version shortly

**Comment by pedro-lb** [comment]
Released - https://github.com/jungsoft/materialui-daterange-picker/releases/tag/1.1.92

**Pull request merged**
